import { ChangeEvent, useEffect, useState } from 'react';
import { Archive, FileAudio, FileImage, FileText, Image, Search, Upload, Video } from 'lucide-react';
import { api } from '../../lib/api';

export default function MediaLibraryPage() { const [items, setItems] = useState<any[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [message, setMessage] = useState(''); const load = () => { setLoading(true); api.get<any[]>('/media').then(setItems).catch((error) => setMessage(error.message)).finally(() => setLoading(false)); }; useEffect(load, []);
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const data = new FormData(); data.append('file', file); data.append('title', file.name); setUploading(true); try { await api.upload('/media', data); setMessage('Media uploaded and added to the central library.'); load(); } catch (error: any) { setMessage(error.message); } finally { setUploading(false); event.target.value = ''; } };
  const filtered = items.filter((item) => `${item.title} ${item.category} ${item.file_type}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="space-y-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Central storage</p><h1 className="page-heading">Media Library</h1><p className="page-subheading">One reusable, permission-aware home for portraits, documents, audio, video and learning files.</p></div><label className={`btn-dark cursor-pointer ${uploading ? 'pointer-events-none opacity-60' : ''}`}><Upload className="mr-2 h-4 w-4" />{uploading ? 'Uploading…' : 'Upload file'}<input type="file" onChange={upload} accept="image/jpeg,image/png,image/webp,application/pdf,audio/mpeg,audio/wav,audio/ogg,video/mp4" className="hidden" /></label></div>{message && <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{message}</div>}<div className="rounded-2xl border border-[#dfe8e0] bg-white p-4 sm:p-6"><div className="relative max-w-md"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9aa69d]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search media library" className="input-field pl-10" /></div>{loading ? <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[1,2,3,4].map((item) => <div key={item} className="h-52 animate-pulse rounded-xl bg-[#f0f4ef]" />)}</div> : filtered.length ? <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{filtered.map((item) => <article key={item.id} className="overflow-hidden rounded-2xl border border-[#e5ebe6] bg-[#fbfcfa]"><div className="grid h-36 place-items-center bg-[#edf2ed]">{item.file_type?.startsWith('image') ? <img src={item.file_url} alt={item.alt_text || item.title} className="h-full w-full object-cover" /> : <FileIcon type={item.file_type} />}</div><div className="p-4"><h3 className="truncate text-sm font-extrabold" title={item.title}>{item.title}</h3><p className="mt-1 truncate text-[10px] text-[#839188]">{item.file_type} · {formatSize(item.file_size)}</p><div className="mt-3 flex items-center justify-between"><span className="rounded-full bg-[#e9f0e9] px-2 py-1 text-[9px] font-bold text-[#526258]">{item.status}</span><a href={item.file_url} target="_blank" rel="noreferrer" className="text-[10px] font-extrabold text-emerald-800">Preview</a></div></div></article>)}</div> : <div className="rounded-xl border border-dashed border-[#d5dfd6] p-12 text-center"><Image className="mx-auto h-8 w-8 text-[#9aa69d]" /><p className="mt-3 text-sm font-bold">No media in this view</p><p className="mt-1 text-xs text-[#839188]">Upload an approved file to make it reusable across the site and lab.</p></div>}</div></div>; }
function FileIcon({ type }: { type?: string }) { if (type?.startsWith('audio')) return <FileAudio className="h-10 w-10 text-emerald-800" />; if (type?.startsWith('video')) return <Video className="h-10 w-10 text-emerald-800" />; if (type?.includes('pdf')) return <FileText className="h-10 w-10 text-amber-700" />; return <FileImage className="h-10 w-10 text-emerald-800" />; }
function formatSize(size = 0) { if (size < 1024) return `${size} B`; if (size < 1024 * 1024) return `${Math.round(size / 1024)} KB`; return `${(size / 1024 / 1024).toFixed(1)} MB`; }
