import { useEffect, useState } from 'react';
import { Check, ChevronDown, Eye, EyeOff, GripVertical, LayoutTemplate, Save, Settings2 } from 'lucide-react';
import { api } from '../../lib/api';

const blockTypes = ['Hero', 'Welcome', 'Pandit Raghunath Murmu', 'School list', 'Santali Dictionary', 'Ol Chiki Lab', 'Notices', 'Events', 'Gallery', 'Culture', 'Resources', 'Contact', 'Footer'];
export default function PageBuilderPage() {
  const [pages, setPages] = useState<any[]>([]); const [selected, setSelected] = useState<any>(null); const [activeBlock, setActiveBlock] = useState<any>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const load = () => { setLoading(true); api.get<any[]>('/pages').then((items) => { setPages(items); setSelected(items[0] || null); setActiveBlock(items[0]?.blocks?.[0] || null); }).catch(() => setMessage('Could not load pages. Check your session.')).finally(() => setLoading(false)); };
  useEffect(load, []);
  const saveBlock = async () => { if (!activeBlock) return; setSaving(true); try { await api.put(`/page-blocks/${activeBlock.id}`, { ...activeBlock, blockType: activeBlock.block_type, displayOrder: activeBlock.display_order, isVisible: activeBlock.is_visible === 1, config: typeof activeBlock.config === 'string' ? JSON.parse(activeBlock.config || '{}') : activeBlock.config }); setMessage('Block saved to the CMS.'); load(); } catch (error: any) { setMessage(error.message); } finally { setSaving(false); } };
  const updateActive = (key: string, value: any) => setActiveBlock((block: any) => ({ ...block, [key]: value }));
  return <div className="space-y-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Content operations</p><h1 className="page-heading">Page Builder</h1><p className="page-subheading">Reorder, hide and edit the public homepage without touching source code.</p></div><div className="flex gap-2"><a href="/" target="_blank" className="btn-light"><Eye className="mr-2 h-4 w-4" /> Preview</a><button onClick={saveBlock} disabled={saving || !activeBlock} className="btn-dark"><Save className="mr-2 h-4 w-4" />{saving ? 'Saving…' : 'Save block'}</button></div></div>{message && <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800"><Check className="mr-2 inline h-4 w-4" />{message}</div>}
    {loading ? <div className="grid gap-5 lg:grid-cols-[260px_1fr]"><div className="h-96 animate-pulse rounded-2xl bg-[#e7ece7]" /><div className="h-96 animate-pulse rounded-2xl bg-[#e7ece7]" /></div> : <div className="grid gap-5 lg:grid-cols-[280px_1fr]">
      <aside className="rounded-2xl border border-[#dfe8e0] bg-white p-4"><div className="mb-4 flex items-center gap-2 text-sm font-extrabold"><LayoutTemplate className="h-4 w-4 text-emerald-700" /> Pages</div>{pages.length ? pages.map((page) => <button key={page.id} onClick={() => { setSelected(page); setActiveBlock(page.blocks?.[0] || null); }} className={`mb-2 w-full rounded-xl px-3 py-3 text-left text-sm font-bold ${selected?.id === page.id ? 'bg-[#173121] text-[#c9f36a]' : 'bg-[#f4f7f3] text-[#607066] hover:bg-[#e9f0e9]'}`}>{page.title || page.slug}<span className="mt-1 block text-[10px] font-medium opacity-60">{page.status} · {page.blocks?.length || 0} blocks</span></button>) : <Empty label="No CMS pages have been seeded yet." />}</aside>
      <div className="grid gap-5 xl:grid-cols-[1fr_320px]"> <section className="rounded-2xl border border-[#dfe8e0] bg-white p-4 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[#91a097]">{selected?.slug || 'Homepage'}</p><h2 className="mt-1 text-lg font-extrabold">Section order</h2></div><span className="rounded-full bg-amber-100 px-3 py-1 text-[10px] font-extrabold text-amber-800">Draft changes</span></div>{selected?.blocks?.length ? <div className="space-y-2">{selected.blocks.map((block: any, index: number) => <button key={block.id} onClick={() => setActiveBlock(block)} className={`flex w-full items-center gap-3 rounded-xl border px-3 py-3 text-left transition ${activeBlock?.id === block.id ? 'border-emerald-700 bg-emerald-50' : 'border-[#e5ebe6] hover:bg-[#f5f8f4]'}`}><GripVertical className="h-4 w-4 text-[#a1ada4]" /><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#173121] text-xs font-extrabold text-[#c9f36a]">{String(index + 1).padStart(2, '0')}</span><span className="flex-1"><strong className="block text-sm">{block.title || block.block_type}</strong><span className="text-[10px] uppercase tracking-wide text-[#8b998f]">{block.block_type}</span></span>{block.is_visible ? <Eye className="h-4 w-4 text-emerald-700" /> : <EyeOff className="h-4 w-4 text-[#a1ada4]" />}</button>)}</div> : <Empty label="Add sections from the CMS setup to start building your page." />}</section>
        <aside className="rounded-2xl border border-[#dfe8e0] bg-white p-5"><div className="flex items-center gap-2 text-sm font-extrabold"><Settings2 className="h-4 w-4 text-emerald-700" /> Design controls</div>{activeBlock ? <div className="mt-5 space-y-4"><Field label="Block title" value={activeBlock.title || ''} onChange={(value) => updateActive('title', value)} /><label className="block"><span className="field-label">Block type</span><select value={activeBlock.block_type} onChange={(event) => updateActive('block_type', event.target.value)} className="input-field">{blockTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label className="block"><span className="field-label">Content</span><textarea rows={6} value={activeBlock.content || ''} onChange={(event) => updateActive('content', event.target.value)} className="input-field resize-none" placeholder="Approved copy for this block" /></label><label className="flex items-center gap-3 rounded-xl bg-[#f4f7f3] p-3 text-sm font-bold"><input type="checkbox" checked={activeBlock.is_visible === 1 || activeBlock.is_visible === true} onChange={(event) => updateActive('is_visible', event.target.checked ? 1 : 0)} className="h-4 w-4 accent-emerald-800" /> Visible on public site</label><p className="text-xs leading-6 text-[#75837a]">Advanced visual controls are stored in the block config JSON: background, spacing, colors, radius, shadow, animation and responsive visibility.</p></div> : <Empty label="Select a section to edit its copy, visibility and design configuration." />}</aside></div>
    </div>}
  </div>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block"><span className="field-label">{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} className="input-field" /></label>; }
function Empty({ label }: { label: string }) { return <div className="rounded-xl border border-dashed border-[#d5dfd6] p-7 text-center text-sm leading-6 text-[#839188]">{label}</div>; }
