import { useEffect, useState } from 'react';
import { ArrowUpRight, BookOpen, CalendarDays, FileText, Image as ImageIcon, Link2, ShieldAlert } from 'lucide-react';
import PublicPageHero from '../../components/public/PublicPageHero';
import { api } from '../../lib/api';

const demoProfile = { name: 'Pandit Raghunath Murmu', summary: 'A heritage profile managed by BRANCH ASECA DANGACHUA.', biography: 'This is a DEMO DATA profile. Authorized editors can replace it with an officially verified biography, source references, timeline and approved photographs without changing source code.', photo: '', timeline: [], contributions: [], images: [], references: [], status: 'demo' };
export default function PanditRaghunathMurmuPage() {
  const [profile, setProfile] = useState<any>(demoProfile);
  const [loading, setLoading] = useState(true);
  useEffect(() => { api.get<any>('/public/historical/pandit-raghunath-murmu').then(setProfile).catch(() => undefined).finally(() => setLoading(false)); }, []);
  return <div className="bg-[#f4f2e9]">
    <PublicPageHero eyebrow="Santali heritage profile" title="Remembering the people" accent="who made learning possible." description="An editorial space for verified biography, photographs, contributions and references—kept open for responsible community stewardship." />
    <section id="page-content" className="px-5 py-16 sm:px-8 sm:py-24 lg:px-10"><div className="mx-auto max-w-7xl">
      <div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div className="relative overflow-hidden rounded-[2rem] bg-[#0b1710] p-5 text-white sm:p-8">{profile.photo ? <img src={profile.photo} alt={profile.name} className="aspect-[4/4.5] w-full rounded-[1.5rem] object-cover" /> : <div className="grid aspect-[4/4.5] place-items-center rounded-[1.5rem] border border-white/10 bg-[#132219]"><span className="font-olchiki text-[10rem] text-lime-300/20">ᱚ</span><span className="absolute bottom-12 rounded-full bg-amber-300 px-3 py-1 text-[10px] font-extrabold uppercase tracking-[.16em] text-[#0b1710]">Portrait pending verified upload</span></div>}<div className="absolute left-10 top-10 rounded-full border border-white/10 bg-[#0b1710]/80 px-3 py-2 text-[10px] font-bold text-lime-300 backdrop-blur">{profile.status === 'demo' ? 'DEMO PROFILE' : 'EDITORIAL PROFILE'}</div></div>
        <div><p className="public-kicker public-kicker-dark"><span />Heritage profile</p><h2 className="public-display mt-6 text-5xl font-extrabold leading-[.96] tracking-[-.055em] text-[#101a14] sm:text-7xl">{profile.name}</h2><p className="mt-7 max-w-xl text-lg leading-8 text-[#34483c]/70">{profile.summary}</p><div className="mt-8 flex flex-wrap gap-3"><span className="rounded-full border border-emerald-700/20 bg-emerald-100 px-4 py-2 text-xs font-bold text-emerald-800">Source-aware record</span><span className="rounded-full border border-amber-500/25 bg-amber-100 px-4 py-2 text-xs font-bold text-amber-800">No unsourced facts</span></div><div className="mt-10 rounded-2xl border border-amber-500/20 bg-amber-100/60 p-5"><div className="flex gap-3"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-amber-800" /><p className="text-sm leading-7 text-amber-950/75">This profile distinguishes administrator-provided editorial content from verified historical information. Every timeline item and image can carry a reference, credit and permission note.</p></div></div></div></div>
      <div className="mt-20 grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="public-kicker public-kicker-dark"><span />Biography</p><h2 className="public-display mt-5 text-4xl font-extrabold tracking-[-.05em]">A page ready for<br /><em className="not-italic text-emerald-700">official memory.</em></h2></div><div className="prose max-w-none text-base leading-8 text-[#34483c]/75"><p>{profile.biography}</p><p className="mt-6">Authorized editors can maintain long-form biography, childhood, education, language work, Ol Chiki contribution, legacy and important dates using the heritage editor.</p></div></div>
    </div></section>
    <section className="bg-[#0b1710] px-5 py-20 text-white sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="public-kicker"><span />Verified timeline</p><h2 className="public-display mt-5 text-5xl font-extrabold tracking-[-.05em]">Dates with<br /><span className="text-lime-300">context.</span></h2></div><div className="divide-y divide-white/10 border-y border-white/10">{loading ? <div className="py-10 text-white/50">Loading heritage record…</div> : profile.timeline?.length ? profile.timeline.map((item: any) => <div key={item.id} className="grid gap-3 py-7 sm:grid-cols-[120px_1fr]"><span className="font-bold text-lime-300">{item.date_label}</span><div><h3 className="font-extrabold">{item.title}</h3><p className="mt-2 text-sm leading-7 text-white/50">{item.description}</p>{item.source_note && <p className="mt-3 text-[10px] uppercase tracking-[.14em] text-white/30">Reference: {item.source_note}</p>}</div></div>) : <div className="py-10 text-sm leading-7 text-white/50">No verified timeline items are published yet. The organization can add dates, descriptions, images and references from the admin editor.</div>}</div></div></div></section>
    <section className="px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-2"><ContentList icon={BookOpen} title="Contributions" items={profile.contributions} empty="Verified contribution cards will appear here." /><ContentList icon={ImageIcon} title="Historical image gallery" items={profile.images} empty="Approved images, captions, credits and copyright information will appear here." /></div><div className="mt-16 rounded-[2rem] bg-amber-300 p-8 text-[#0b1710] sm:p-12"><div className="flex items-start gap-4"><FileText className="mt-1 h-6 w-6" /><div><h2 className="public-display text-3xl font-extrabold">Sources & references</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-[#34483c]/70">Historical content is published with source context. The reference manager supports publications, authors, dates, URLs, documents and verification status.</p>{profile.references?.length ? <div className="mt-6 grid gap-3 sm:grid-cols-2">{profile.references.map((reference: any) => <a key={reference.id} href={reference.url || '#'} className="rounded-xl bg-white/40 p-4 text-sm font-bold">{reference.title}<Link2 className="ml-2 inline h-3.5 w-3.5" /></a>)}</div> : <span className="mt-5 inline-flex rounded-full border border-[#0b1710]/15 px-4 py-2 text-xs font-bold">No references published yet</span>}</div></div></div></div></section>
  </div>;
}
function ContentList({ icon: Icon, title, items, empty }: { icon: typeof BookOpen; title: string; items?: any[]; empty: string }) { return <div><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-800 text-lime-300"><Icon className="h-5 w-5" /></span><h2 className="public-display text-3xl font-extrabold tracking-[-.04em]">{title}</h2></div>{items?.length ? <div className="mt-6 space-y-3">{items.map((item: any) => <article key={item.id} className="rounded-2xl border border-[#14251b]/10 bg-white/60 p-5"><h3 className="font-extrabold">{item.title || item.caption}</h3><p className="mt-2 text-sm leading-7 text-[#34483c]/65">{item.description || item.credit || 'Approved editorial content.'}</p></article>)}</div> : <div className="mt-6 rounded-2xl border border-dashed border-[#14251b]/15 p-7 text-sm leading-7 text-[#34483c]/55">{empty}</div>}</div>; }
